# Generated by Django 3.2.9 on 2021-11-03 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Preform',
                'verbose_name_plural': 'Preforms',
            },
        ),
        migrations.CreateModel(
            name='DetailPreform',
            fields=[
                ('detail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.detail')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preform.preform')),
            ],
            options={
                'verbose_name': 'DetailPreform',
                'verbose_name_plural': 'DetailPreforms',
            },
            bases=('core.detail',),
        ),
    ]
