# Generated by Django 3.2.9 on 2021-11-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preform',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='preform',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
