# Generated by Django 3.2.9 on 2021-11-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preform', '0002_auto_20211103_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='preform',
            name='identifier',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
