# Generated by Django 3.2.9 on 2021-11-03 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_company_logo'),
        ('preform', '0003_preform_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='preform',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client.branch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preform',
            name='identifier',
            field=models.PositiveSmallIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='preform',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'executed'), (1, 'Validated'), (2, 'Canceled')], default=0),
        ),
        migrations.AlterField(
            model_name='preform',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=8),
        ),
    ]
