# Generated by Django 3.2.9 on 2021-11-03 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preform', '0004_auto_20211103_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailpreform',
            old_name='item',
            new_name='preform',
        ),
    ]
