# Generated by Django 3.2.9 on 2021-11-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preform', '0005_rename_item_detailpreform_preform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preform',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=8, null=True),
        ),
    ]
