# Generated by Django 3.2.9 on 2021-11-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preform', '0006_alter_preform_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preform',
            name='identifier',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
    ]
