# Generated by Django 3.2.9 on 2021-11-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20211103_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
